export { default as ErrorBlock } from './error-block';
export { default as InputField } from './input-field';
export { default as Input } from './input';
export { default as Heading } from './heading';
export { default as Button } from './button';
// export { RegistrationForm } from './registristration-form';
export { default as Field } from './field';
export { default as ListContacts } from './list-contacts';
export { default as ContactCard } from './contact-card';
export { default as Message } from './message';
export { default as ListMessages } from './list-messages';
export { default as MessageBar } from './message-bar';
export { default as Avatar } from './avatar';
export { default as PersonalData } from './personal-data';
// export { StatusMessage } from './status-message';
// export { TempMenu } from './tempMenu';
